<a href="https://colab.research.google.com/github/anshulkumarsingh1007/ml.bootcamp/blob/main/b2_session4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#first code snippet
marks=[78,63,62]
avg=sum(marks)/ len(marks)
print(avg)

67.66666666666667


In [ ]:
#second code snipptt
def caclculate_average(marks):
  return sum(marks)/ len(marks)
marks=[78,63,62]
print(caclculate_average(marks))

67.66666666666667


In [ ]:
#reusability
#paramaters
#write a simple function (resusable) to filter students pass or fail based on the condition: that the student gets 27

In [ ]:
def get_result_status(score):
    if score >= 27:
        return "Pass"
    return "Fail"

print(get_result_status(85))
print(get_result_status(32))


In [ ]:
#Python List
General purpose
can hold any data types or mixed data types
normal programming
operations need loops

In [ ]:
#numpy array
numerical data focused
usually holds one main numeric type
mathematical operations
operations can apply to the whole array

In [ ]:
marks=[78,63,62]
print (marks+10)

TypeError: can only concatenate list (not "int") to list

In [ ]:
import numpy as np

marks_array =np.array([78,63,62])
print(marks_array+10)

[88 73 72]


In [ ]:
#shape: the structure of the array
#index:the position of the an element
#axis: direction of the calculation across rows or columns or XYZ axis

In [ ]:
import numpy as np

arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)


matrix =np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
#slicing?
grid = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]
])
print(grid[0,0])
print(grid[0])
print(grid[:,0])
print(grid[0:3, 0:3])
print(grid[1:4, 1:4])

11
[11 12 13 14 15]
[11 21 31 41 51]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[22 23 24]
 [32 33 34]
 [42 43 44]]


In [ ]:
marks = np.array([78, 91, 55, 72, 40, 88])

print(marks > 70)

high_scores = marks[marks > 70]
print(high_scores)


[ True  True False  True False  True]
[78 91 72 88]


In [ ]:
marks = np.array([78, 91, 55, 72, 40, 88])

print(marks.mean())
print(marks.min())
print(marks.max())
print(marks.sum())


70.66666666666667
40
91
424


In [ ]:
#first the class avaerage
find the highest score
find the lowest high_scores
coundt students above 75


In [ ]:
from google.colab import files
uploaded =files.upload()

Saving session4_dummy_students_data.csv to session4_dummy_students_data.csv


In [ ]:
import pandas as pd

df = pd.read_csv("session4_dummy_students_data.csv")
print(df)


    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [ ]:
print(df.head())
print(df.columns)
print(df.shape)
print(df.info())


   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78  
4                   45  
Index(['student_id', 'name', 'age', 'city', 'math', 'sci

In [ ]:
math_scores = df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())


[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [ ]:
#calculate the average score accroess the other two subjects
#filtering
#top students average  more than or equal to 85
df["average"] = df[["math", "science", "english"]].mean(axis=1)
print(df[["name", "math", "science", "english", "average"]])


top_students = df[df["average"] >= 85]
print(top_students[["name", "average"]])





      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667
      name    average
1     Diya  

In [ ]:
#low attendance, if attendance percentage is less than 75 then
low_attendance = df[df["attendance_percent"] < 75]
print(low_attendance[["name", "attendance_percent"]])

      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66


In [ ]:
#mathura students

mathura_students = df[df["city"] == "Mathura"]
print(mathura_students[["name", "city","average"]])

      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000


In [ ]:
#STUDENT PERFORMANCE ANALYSER
•	Read session4_dummy_students.csv.
•	Create an average column using math, science, and english.
•	Create a result column: Pass if average >= 40, otherwise Fail.
•	Print class average.
•	Print highest average and lowest average subject wise.
•	Print top student or students.
•	Print students with attendance below 75.
•	Print students who submitted fewer than 6 assignments.

In [ ]:
import pandas as pd
import numpy as np


def get_result(avg):
  if avg>=40:
    return "Pass"
  return "fail"


df = pd.read_csv("session4_dummy_students_data.csv")


df["average"] = df[["math", "science", "english"]].mean(axis=1)
df["result"] = df["average"].apply(get_result)


print("Full Data:")
print(df)


print("Class average:", df["average"].mean())
print("Highest average:", df["average"].max())
print("Lowest average:", df["average"].min())


low_assignment_students = df[df["assignments_submitted"] < 6]
print("Students with fewer than 6 assignments:")
print(low_assignment_students[["name", "assignments_submitted"]])



Full Data:
    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  